import React, { useState } from 'react';
import { SpriteChangeRecord, OwnershipStatus } from '../types';
import { getRarityColor, getVariantBadge } from '../utils/theme';
import {
  X,
  ClipboardList,
  RotateCcw,
  Trash2,
  Check,
  Copy,
  Package,
  XCircle,
  ArrowRight,
  Sparkles,
  Search,
} from 'lucide-react';
import { FortniteCrown } from './FortniteCrown';

interface ChangesRundownModalProps {
  isOpen: boolean;
  onClose: () => void;
  changes: SpriteChangeRecord[];
  usernameA: string;
  usernameB: string;
  onRevertItem: (spriteId: string, player: 'A' | 'B') => void;
  onClearAllChanges: () => void;
}

export const ChangesRundownModal: React.FC<ChangesRundownModalProps> = ({
  isOpen,
  onClose,
  changes,
  usernameA,
  usernameB,
  onRevertItem,
  onClearAllChanges,
}) => {
  const [filterPlayer, setFilterPlayer] = useState<'ALL' | 'A' | 'B'>('ALL');
  const [searchFilter, setSearchFilter] = useState('');
  const [copied, setCopied] = useState(false);
  const [confirmClear, setConfirmClear] = useState(false);

  if (!isOpen) return null;

  const filteredChanges = changes.filter((ch) => {
    if (filterPlayer !== 'ALL' && ch.player !== filterPlayer) return false;
    if (searchFilter.trim()) {
      const q = searchFilter.toLowerCase();
      return (
        ch.spriteName.toLowerCase().includes(q) ||
        ch.variant.toLowerCase().includes(q) ||
        ch.rarity.toLowerCase().includes(q)
      );
    }
    return true;
  });

  const countA = changes.filter((c) => c.player === 'A').length;
  const countB = changes.filter((c) => c.player === 'B').length;

  const renderStatusBadge = (status: OwnershipStatus) => {
    if (status === 'mastered') {
      return (
        <span className="inline-flex items-center gap-1 rounded-md bg-amber-400/20 px-2 py-0.5 text-[11px] font-bold text-amber-300 border border-amber-400/40">
          <FortniteCrown variant="gold" size="xs" />
          Mastered (L5)
        </span>
      );
    }
    if (status === 'owned') {
      return (
        <span className="inline-flex items-center gap-1 rounded-md bg-blue-500/20 px-2 py-0.5 text-[11px] font-medium text-blue-300 border border-blue-500/30">
          <Package className="h-3 w-3 text-blue-400" />
          Owned (L1)
        </span>
      );
    }
    return (
      <span className="inline-flex items-center gap-1 rounded-md bg-zinc-800 px-2 py-0.5 text-[11px] text-zinc-400 border border-zinc-700">
        <XCircle className="h-3 w-3 text-zinc-500" />
        Not Owned
      </span>
    );
  };

  const generateChecklistText = () => {
    let out = `📋 **Fortnite.gg Sprite Locker Sync Checklist**\n`;
    out += `Use this rundown to update your collections on fortnite.gg/sprites:\n\n`;

    const aChanges = changes.filter((c) => c.player === 'A');
    if (aChanges.length > 0) {
      out += `👤 **${usernameA} (${aChanges.length} updates):**\n`;
      aChanges.forEach((c) => {
        const targetDesc =
          c.currentStatus === 'mastered'
            ? '👑 Mastered (Level 5)'
            : c.currentStatus === 'owned'
            ? '📦 Owned (Level 1)'
            : '❌ Not Owned';
        const origDesc =
          c.originalStatus === 'mastered'
            ? 'Mastered'
            : c.originalStatus === 'owned'
            ? 'Owned'
            : 'Not Owned';
        out += `- [ ] **${c.spriteName}** (${c.rarity.toUpperCase()}${c.variant !== 'base' ? `, ${c.variant}` : ''}): Change from ${origDesc} ➔ **${targetDesc}**\n`;
      });
      out += `\n`;
    }

    const bChanges = changes.filter((c) => c.player === 'B');
    if (bChanges.length > 0) {
      out += `👤 **${usernameB} (${bChanges.length} updates):**\n`;
      bChanges.forEach((c) => {
        const targetDesc =
          c.currentStatus === 'mastered'
            ? '👑 Mastered (Level 5)'
            : c.currentStatus === 'owned'
            ? '📦 Owned (Level 1)'
            : '❌ Not Owned';
        const origDesc =
          c.originalStatus === 'mastered'
            ? 'Mastered'
            : c.originalStatus === 'owned'
            ? 'Owned'
            : 'Not Owned';
        out += `- [ ] **${c.spriteName}** (${c.rarity.toUpperCase()}${c.variant !== 'base' ? `, ${c.variant}` : ''}): Change from ${origDesc} ➔ **${targetDesc}**\n`;
      });
    }

    out += `\nSync generated by Fortnite Sprite Trader`;
    return out;
  };

  const handleCopyChecklist = () => {
    navigator.clipboard.writeText(generateChecklistText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
      <div className="relative flex max-h-[90vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl border border-zinc-700 bg-zinc-950 shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-zinc-800 p-5 bg-zinc-900/60">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-purple-500/20 text-purple-400 border border-purple-500/30">
              <ClipboardList className="h-5 w-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base font-bold text-white">Client-Side Changes Rundown</h3>
                <span className="rounded-full bg-purple-500/20 border border-purple-500/40 px-2 py-0.5 text-xs font-bold text-purple-300">
                  {changes.length} {changes.length === 1 ? 'change' : 'changes'}
                </span>
              </div>
              <p className="text-xs text-zinc-400">
                Track all local edits to sprite ownership and mastery so you can easily sync them back to Fortnite.gg
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="rounded-lg p-1.5 text-zinc-400 hover:bg-zinc-800 hover:text-white transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Toolbar & Filter Bar */}
        <div className="border-b border-zinc-800 bg-zinc-900/30 p-4 space-y-3">
          <div className="flex flex-wrap items-center justify-between gap-3">
            {/* Player filter tabs */}
            <div className="flex rounded-xl bg-zinc-900 p-1 border border-zinc-800">
              <button
                onClick={() => setFilterPlayer('ALL')}
                className={`rounded-lg px-3 py-1 text-xs font-semibold transition-all ${
                  filterPlayer === 'ALL'
                    ? 'bg-zinc-700 text-white shadow'
                    : 'text-zinc-400 hover:text-zinc-200'
                }`}
              >
                All ({changes.length})
              </button>
              <button
                onClick={() => setFilterPlayer('A')}
                className={`flex items-center gap-1.5 rounded-lg px-3 py-1 text-xs font-semibold transition-all ${
                  filterPlayer === 'A'
                    ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 shadow'
                    : 'text-zinc-400 hover:text-cyan-300'
                }`}
              >
                <span className="h-2 w-2 rounded-full bg-cyan-400" />
                {usernameA} ({countA})
              </button>
              <button
                onClick={() => setFilterPlayer('B')}
                className={`flex items-center gap-1.5 rounded-lg px-3 py-1 text-xs font-semibold transition-all ${
                  filterPlayer === 'B'
                    ? 'bg-rose-500/20 text-rose-300 border border-rose-500/40 shadow'
                    : 'text-zinc-400 hover:text-rose-300'
                }`}
              >
                <span className="h-2 w-2 rounded-full bg-rose-400" />
                {usernameB} ({countB})
              </button>
            </div>

            {/* Quick Actions */}
            <div className="flex items-center gap-2">
              <button
                onClick={handleCopyChecklist}
                disabled={changes.length === 0}
                className="flex items-center gap-1.5 rounded-xl bg-purple-600 px-3.5 py-1.5 text-xs font-bold text-white shadow-md shadow-purple-900/30 hover:bg-purple-500 disabled:opacity-50 transition-all"
              >
                {copied ? (
                  <>
                    <Check className="h-3.5 w-3.5 text-emerald-300" />
                    <span>Checklist Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="h-3.5 w-3.5" />
                    <span>Copy Fortnite.gg Checklist</span>
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Search box if there are multiple changes */}
          {changes.length > 3 && (
            <div className="relative">
              <Search className="absolute left-3 top-2.5 h-3.5 w-3.5 text-zinc-500" />
              <input
                type="text"
                placeholder="Filter changed sprites by name, variant, or rarity..."
                value={searchFilter}
                onChange={(e) => setSearchFilter(e.target.value)}
                className="w-full rounded-xl border border-zinc-800 bg-zinc-900/90 py-1.5 pl-9 pr-3 text-xs text-zinc-200 placeholder-zinc-500 focus:border-rose-500 focus:outline-none"
              />
            </div>
          )}
        </div>

        {/* Change List Content */}
        <div className="flex-1 overflow-y-auto p-4 space-y-2.5 max-h-[50vh]">
          {changes.length === 0 ? (
            <div className="flex flex-col items-center justify-center p-12 text-center text-zinc-500">
              <Sparkles className="h-10 w-10 text-zinc-600 mb-2 opacity-60" />
              <p className="text-sm font-semibold text-zinc-300">No Manual Edits Made</p>
              <p className="text-xs text-zinc-500 max-w-sm mt-1">
                When you change sprite ownership or mastery statuses directly on the grid or table, they will be logged here for easy Fortnite.gg syncing.
              </p>
            </div>
          ) : filteredChanges.length === 0 ? (
            <div className="p-8 text-center text-xs text-zinc-500">
              No changes match the selected filter.
            </div>
          ) : (
            filteredChanges.map((change) => {
              const rarityTheme = getRarityColor(change.rarity);
              const variantInfo = getVariantBadge(change.variant);
              const isPlayerA = change.player === 'A';

              return (
                <div
                  key={`${change.spriteId}-${change.player}`}
                  className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 rounded-xl border border-zinc-800 bg-zinc-900/60 p-3 hover:bg-zinc-900 transition-colors"
                >
                  {/* Left: Sprite info + player tag */}
                  <div className="flex items-center gap-3">
                    <img
                      src={change.iconUrl || 'https://fortnite.gg/img/icon.jpg'}
                      alt={change.spriteName}
                      className="h-11 w-11 rounded-lg border border-zinc-700 bg-zinc-950 object-contain p-0.5 shrink-0"
                      referrerPolicy="no-referrer"
                    />

                    <div>
                      <div className="flex items-center gap-1.5 mb-0.5">
                        <span
                          className={`rounded px-1.5 py-0.2 text-[10px] font-black uppercase ${
                            isPlayerA
                              ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40'
                              : 'bg-rose-500/20 text-rose-300 border border-rose-500/40'
                          }`}
                        >
                          {isPlayerA ? `Player A (${usernameA})` : `Player B (${usernameB})`}
                        </span>
                        <span
                          className={`rounded px-1.5 py-0.2 text-[9px] font-bold uppercase ${rarityTheme.badgeBg}`}
                        >
                          {change.rarity}
                        </span>
                        {change.variant !== 'base' && (
                          <span
                            className={`rounded px-1.5 py-0.2 text-[9px] font-bold ${variantInfo.bgClass} ${variantInfo.textColor}`}
                          >
                            {variantInfo.label}
                          </span>
                        )}
                      </div>
                      <div className="text-sm font-bold text-white">{change.spriteName}</div>
                    </div>
                  </div>

                  {/* Middle: Before & After Transition */}
                  <div className="flex items-center gap-2 self-start sm:self-center pl-14 sm:pl-0">
                    {renderStatusBadge(change.originalStatus)}
                    <ArrowRight className="h-3.5 w-3.5 text-zinc-500 shrink-0" />
                    {renderStatusBadge(change.currentStatus)}
                  </div>

                  {/* Right: Individual Revert Button */}
                  <div className="flex items-center justify-end">
                    <button
                      onClick={() => onRevertItem(change.spriteId, change.player)}
                      className="flex items-center gap-1 rounded-lg border border-zinc-700 bg-zinc-800/80 px-2.5 py-1 text-xs text-zinc-300 hover:bg-zinc-700 hover:text-white transition-colors"
                      title="Revert to original state"
                    >
                      <RotateCcw className="h-3 w-3" />
                      <span>Revert</span>
                    </button>
                  </div>
                </div>
              );
            })
          )}
        </div>

        {/* Footer */}
        <div className="flex flex-wrap items-center justify-between gap-3 border-t border-zinc-800 p-4 bg-zinc-950">
          <div>
            {confirmClear ? (
              <div className="flex items-center gap-2">
                <span className="text-xs text-rose-400 font-semibold">Clear all {changes.length} changes?</span>
                <button
                  onClick={() => {
                    onClearAllChanges();
                    setConfirmClear(false);
                  }}
                  className="rounded-lg bg-rose-600 px-3 py-1 text-xs font-bold text-white hover:bg-rose-500 transition-colors"
                >
                  Yes, Clear All
                </button>
                <button
                  onClick={() => setConfirmClear(false)}
                  className="rounded-lg border border-zinc-700 bg-zinc-900 px-2.5 py-1 text-xs text-zinc-300 hover:bg-zinc-800 transition-colors"
                >
                  Cancel
                </button>
              </div>
            ) : (
              <button
                onClick={() => setConfirmClear(true)}
                disabled={changes.length === 0}
                className="flex items-center gap-1.5 rounded-lg border border-rose-500/30 bg-rose-500/10 px-3 py-1.5 text-xs font-semibold text-rose-300 hover:bg-rose-500/20 disabled:opacity-40 transition-colors"
              >
                <Trash2 className="h-3.5 w-3.5" />
                <span>Clear All Changes</span>
              </button>
            )}
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-2 text-xs font-semibold text-zinc-300 hover:bg-zinc-800 transition-colors"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
